// <auto-generated />
using HandOffApiCli.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandOffApiCli.Migrations
{
    [DbContext(typeof(HandOffContext))]
    [Migration("20221214033312_Employee")]
    partial class Employee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandOffApiCli.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeFirstName = "Paul",
                            EmployeeLastName = "Ford"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeFirstName = "Amy",
                            EmployeeLastName = "Eisenberg"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeFirstName = "Tom",
                            EmployeeLastName = "Hardy"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeFirstName = "John",
                            EmployeeLastName = "Grossman"
                        },
                        new
                        {
                            Id = 5,
                            EmployeeFirstName = "Olivia",
                            EmployeeLastName = "Mundain"
                        },
                        new
                        {
                            Id = 6,
                            EmployeeFirstName = "Jessica",
                            EmployeeLastName = "Stone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
